### ISSUE TITLE
Show "Place" View

### ISSUE THREAD

**Issue by Ronapj1991** [Code-the-Dream-School/firefish-practicum#36]
This task would rely on [#28](https://github.com/Code-the-Dream-School/firefish-practicum/issues/28) 

When a user clicks on a specific place from the index view, the user should be redirected to a show view of that place.

### For an Attraction

Display the following:

- Show the image/if an image is not present in the database, add a placeholder
- name
- email
- phone
- website
- address
- Wheelchair Accessible?
- Restrooms Available

### For a Hotel

Display the following:

- Show the image/if an image is not present in the database, add a placeholder
- name
- email
- phone
- website
- address
- Wheelchair Accessible?
- Number of Stars

### For a Restaurant

Display the following:

- Show the image/if an image is not present in the database, add a placeholder
- name
- email
- phone
- website
- address
- wheelchair accessible?
- does it have indoor seating?
- outdoor seating?

**Comment by dsinn** [comment]
Closed by #44
